### ISSUE TITLE
AttributeError: 'QueryCountMiddleware' object has no attribute 'get_response'

### ISSUE THREAD

**Issue by pyprism** [bradmontgomery/django-querycount#14]
Test client throws above error when I try to test this snippet 

```
class IndexPageTest(TestCase):
    def setUp(self):
        self.client = Client()

    def test_uses_login_template(self):
        response = self.client.get('/')
        self.assertTemplateUsed(response, 'index.html')
```
Although this code is perfectly working if I disable the middleware from settings.py .

Here is full output 

```
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_uses_login_template (....tests.IndexPageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../tests.py", line 11, in test_uses_login_template
    response = self.client.get('/')
  File "....env/lib/python3.5/site-packages/django/test/client.py", line 529, in get
    **extra)
  File "....env/lib/python3.5/site-packages/django/test/client.py", line 333, in get
    return self.generic('GET', path, secure=secure, **r)
  File ".../.env/lib/python3.5/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File ".../.env/lib/python3.5/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "....env/lib/python3.5/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File ".../.env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "....env/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
AttributeError: 'QueryCountMiddleware' object has no attribute 'get_response'

----------------------------------------------------------------------
Ran 1 test in 2.621s

FAILED (errors=1)

```

**Comment by bradmontgomery** [comment]
@pyprism Thank you for reporting this. It should be fixed in version 0.6.0, which is [now on pypi](https://pypi.python.org/pypi/django-querycount).  Sorry for taking so long to get around to this.
