### ISSUE TITLE
WHERE_CLAUSE_REGEX bad escape problem

### ISSUE THREAD

**Issue by ckcollab** [bradmontgomery/django-querycount#32]
First of all: thanks so much for this module! I use it a shitload and it, basically, never lets me down. Appreciate it :)

I'm getting this little problemo with Django 4.2, Python 3.11, Psycopg 3.1.8:

```py
Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/querycount/middleware.py", line 117, in process_response
    self._count_queries("response")
  File "/usr/local/lib/python3.11/site-packages/querycount/middleware.py", line 85, in _count_queries
    sql = self.WHERE_CLAUSE_REGEX.sub(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 317, in _subx
    template = _compile_repl(template, pattern)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 308, in _compile_repl
    return _parser.parse_template(repl, pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/_parser.py", line 1078, in parse_template
    raise s.error('bad escape %s' % this, len(this)) from None
re.error: bad escape \x at position 55
```

Not exactly sure what's causing this, but thought it might be worth posting an issue about. Maybe data changed in some way between Django 4.1 and 4.2?

**Comment by ptwobrussell** [comment]
I hit a nearly identical issue with a similar stack trace after a routine dependencies upgrade -- just a different escape character.

A common thread is that I also went from Django 4.1 => 4.2, so perhaps that is worth a closer look.

Nothing jumps out at me in the Django 4.2 release notes, but perhaps this will mean something to someone else more familiar with the internals of this library.

https://docs.djangoproject.com/en/4.2/releases/4.2/#database-backend-api

**Comment by Shivaank121** [comment]
Getting similar issue with Django 3.2, [GeoDjango](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/), Postgres with postgis extension for only queries like this:

```
from django.contrib.gis.geos import Point
from django.contrib.gis.measure import Distance  

lat = 52.5
lng = 1.0
radius = 10
point = Point(lng, lat)    
Place.objects.filter(location__distance_lt=(point, Distance(km=radius))) 

```

<img width="1159" alt="Screen Shot 2023-10-06 at 6 55 04 PM" src="https://github.com/bradmontgomery/django-querycount/assets/20373727/4a397df4-4691-4bef-8183-b4e9cb74ebda">

Other ORM queries working fine.

https://gis.stackexchange.com/questions/141533/geodjango-find-all-points-within-radius

**Comment by danmichaelo** [comment]
There is an unmerged PR that seems to fix this: https://github.com/bradmontgomery/django-querycount/pull/30
